### section A

In [1]:
import pandas as pd

In [6]:
emp=pd.read_csv(r"C:\Users\admin\Documents\Data Analytics\ajun\files\employee_data.csv")

In [7]:
emp

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [8]:
emp.head(5)

   ID         Name Department      City   Job Role   Salary  Exp_Yrs  Rating
0   1   Arun Kumar      Sales   Calicut  Executive  28000.0        3     4.2
1   2   Priya Nair         IT     Kochi  Developer  45000.0        5     4.7
2   3  Rahul Menon         HR   Calicut    Manager  38000.0        7     NaN
3   4    Sneha Das      Sales  Thrissur  Executive  29000.0        2     3.9
4   5      Vijay S         IT     Kochi  Developer  47000.0        6     4.5

In [11]:
emp.shape

(63, 8)

In [15]:
emp.columns

Index(['ID', 'Name', 'Department', 'City', 'Job Role', 'Salary', 'Exp_Yrs',
       'Rating'],
      dtype='object')

In [16]:
emp.dtypes

ID              int64
Name           object
Department     object
City           object
Job Role       object
Salary        float64
Exp_Yrs         int64
Rating        float64
dtype: object

In [17]:
emp.columns.value_counts()

ID            1
Name          1
Department    1
City          1
Job Role      1
Salary        1
Exp_Yrs       1
Rating        1
Name: count, dtype: int64

In [18]:
emp.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

In [19]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          63 non-null     int64
 1   Name        58 non-null     object
 2   Department  63 non-null     object
 3   City        57 non-null     object
 4   Job Role    63 non-null     object
 5   Salary      62 non-null     float64
 6   Exp_Yrs     63 non-null     int64
 7   Rating      58 non-null     float64
dtypes: float64(2), int64(2), object(4)
memory usage: 4.1+ KB

In [20]:
emp.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

In [21]:
emp.describe()

              ID        Salary    Exp_Yrs     Rating
count  63.000000     62.000000  63.000000  58.000000
mean   32.000000  38822.580645   6.063492   4.194828
std    18.330303  12657.239480   3.267005   0.455925
min     1.000000  25000.000000   1.000000   3.400000
25%    16.500000  28000.000000   3.000000   3.800000
50%    32.000000  34000.000000   6.000000   4.200000
75%    47.500000  46500.000000   9.000000   4.600000
max    63.000000  65500.000000  12.000000   4.900000

In [22]:
emp["Salary"].mean()

np.float64(38822.58064516129)

In [24]:
emp.size

504

In [27]:
emp["Department"].unique()

array(['Sales', 'IT', 'HR', 'Finance'], dtype=object)

In [28]:
emp["Department"].nunique()

4

In [34]:
emp["Department"].value_counts().sort_values(ascending=False)

Department
Sales      19
IT         19
HR         16
Finance     9
Name: count, dtype: int64

In [36]:
emp["City"].value_counts()

City
Calicut     18
Kochi       15
Thrissur    12
Palakkad     8
Kannur       4
Name: count, dtype: int64

In [37]:
emp["City"].unique()

array(['Calicut', 'Kochi', 'Thrissur', nan, 'Palakkad', 'Kannur'],
      dtype=object)

In [38]:
emp["Job Role"].unique()

array(['Executive', 'Developer', 'Manager', 'Analyst', 'Lead',
       'Senior Analyst', 'Senior Executive', 'Recruiter', 'QA Engineer',
       'Senior Developer'], dtype=object)

In [39]:
emp["Job Role"].nunique()

10

In [41]:
emp[["Name","Department","Salary"]]

            Name Department   Salary
0     Arun Kumar      Sales  28000.0
1     Priya Nair         IT  45000.0
2    Rahul Menon         HR  38000.0
3      Sneha Das      Sales  29000.0
4        Vijay S         IT  47000.0
..           ...        ...      ...
58  Joseph Kumar    Finance  38500.0
59   Sreeja Devi    Finance  48000.0
60    Priya Nair         IT  45000.0
61       Anoop M         IT  43000.0
62   Jishnu Devi         HR  26000.0

[63 rows x 3 columns]

### Section B

In [42]:
emp.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

In [43]:
emp.duplicated().sum()

np.int64(0)

In [44]:
emp.drop_duplicates()

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [48]:
emp.shape

(63, 8)

In [49]:
emp.drop("ID",axis=1)

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...
58,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [50]:
emp.dropna()

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
7,8,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
8,9,Divya R,HR,Thrissur,Executive,26000.0,1,3.5
10,11,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
12,13,Rajan T,Finance,Calicut,Senior Analyst,41000.0,6,4.0
15,16,Sreeja V,HR,Calicut,Executive,25000.0,1,3.8
17,18,Lakshmi G,Sales,Thrissur,Executive,27000.0,2,3.6
18,19,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
19,20,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
21,22,Jishnu M,Sales,Palakkad,Senior Executive,25000.0,9,3.7
22,23,Sreeja C,Sales,Thrissur,Manager,27000.0,4,4.8
23,24,Rahul Pillai,HR,Palakkad,Executive,36000.0,2,4.2
24,25,Rahul Devi,Sales,Kochi,Manager,26000.0,4,4.7
25,26,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4
27,28,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
28,29,Manoj M,Finance,Kochi,Manager,47500.0,2,4.5
30,31,Suresh Das,HR,Thrissur,Manager,29000.0,8,3.4
31,32,Vishnu Raj,Sales,Palakkad,Senior Executive,28000.0,3,4.0
32,33,Pradeep Kumar,HR,Calicut,Manager,33500.0,4,3.5
33,34,Bindu S,Sales,Kochi,Senior Executive,32500.0,9,3.6
34,35,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
36,37,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
37,38,Sneha Devi,Finance,Calicut,Analyst,44500.0,12,3.9
38,39,Naveen K,Finance,Kannur,Analyst,34000.0,8,4.6
41,42,Sneha Nair,HR,Palakkad,Manager,29000.0,1,4.8
42,43,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
43,44,Jishnu Devi,HR,Thrissur,Executive,32000.0,7,3.6
44,45,Sajith Mathew,Sales,Palakkad,Executive,26000.0,9,3.7
45,46,Nimisha R,HR,Kannur,Recruiter,33500.0,10,4.9
46,47,Fathima K,Sales,Calicut,Executive,33500.0,3,3.8
49,50,Sreekanth Krishnan,HR,Kochi,Manager,28000.0,1,3.9
50,51,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,52,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,53,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
53,54,Lakshmi G,Sales,Thrissur,Manager,26000.0,5,3.9
54,55,Anoop K,Sales,Kochi,Senior Executive,29000.0,1,3.6
55,56,Deepa Thomas,Sales,Kochi,Manager,25500.0,12,4.1
56,57,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4
57,58,Ajay T,HR,Palakkad,Executive,30000.0,7,4.4
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [52]:
emp.shape

(63, 8)

In [58]:
emp.dropna(subset=["Salary"],inplace=True)

In [59]:
emp.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        0
Exp_Yrs       0
Rating        5
dtype: int64

In [75]:
emp[emp["Department"]=="IT"]

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
6,7,Meera Pillai,IT,NaN,Lead,62000.0,9,4.8
10,11,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
13,14,NaN,IT,Thrissur,Developer,44000.0,5,4.4
14,15,Meera Pillai,IT,NaN,Lead,62000.0,9,4.8
19,20,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
26,27,NaN,IT,Kochi,Developer,65500.0,6,4.0
27,28,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
34,35,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
35,36,NaN,IT,Calicut,Lead,42000.0,1,4.7
36,37,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
42,43,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
50,51,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,52,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,53,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
56,57,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3

In [70]:
emp[["Name","Job Role"]]

            Name        Job Role
0     Arun Kumar       Executive
1     Priya Nair       Developer
2    Rahul Menon         Manager
3      Sneha Das       Executive
4        Vijay S       Developer
..           ...             ...
58  Joseph Kumar  Senior Analyst
59   Sreeja Devi  Senior Analyst
60    Priya Nair       Developer
61       Anoop M       Developer
62   Jishnu Devi       Recruiter

[62 rows x 2 columns]

In [76]:
emp.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        0
Exp_Yrs       0
Rating        5
dtype: int64

In [86]:
emp.drop_duplicates(inplace=True)

In [87]:
emp.shape

(62, 8)

In [88]:
emp.drop("ID",axis=1)

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...
58,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [81]:
emp.dropna()

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
7,8,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
8,9,Divya R,HR,Thrissur,Executive,26000.0,1,3.5
10,11,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
12,13,Rajan T,Finance,Calicut,Senior Analyst,41000.0,6,4.0
15,16,Sreeja V,HR,Calicut,Executive,25000.0,1,3.8
17,18,Lakshmi G,Sales,Thrissur,Executive,27000.0,2,3.6
18,19,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
19,20,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
21,22,Jishnu M,Sales,Palakkad,Senior Executive,25000.0,9,3.7
22,23,Sreeja C,Sales,Thrissur,Manager,27000.0,4,4.8
23,24,Rahul Pillai,HR,Palakkad,Executive,36000.0,2,4.2
24,25,Rahul Devi,Sales,Kochi,Manager,26000.0,4,4.7
25,26,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4
27,28,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
28,29,Manoj M,Finance,Kochi,Manager,47500.0,2,4.5
30,31,Suresh Das,HR,Thrissur,Manager,29000.0,8,3.4
31,32,Vishnu Raj,Sales,Palakkad,Senior Executive,28000.0,3,4.0
32,33,Pradeep Kumar,HR,Calicut,Manager,33500.0,4,3.5
33,34,Bindu S,Sales,Kochi,Senior Executive,32500.0,9,3.6
34,35,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
36,37,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
37,38,Sneha Devi,Finance,Calicut,Analyst,44500.0,12,3.9
38,39,Naveen K,Finance,Kannur,Analyst,34000.0,8,4.6
41,42,Sneha Nair,HR,Palakkad,Manager,29000.0,1,4.8
42,43,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
43,44,Jishnu Devi,HR,Thrissur,Executive,32000.0,7,3.6
44,45,Sajith Mathew,Sales,Palakkad,Executive,26000.0,9,3.7
45,46,Nimisha R,HR,Kannur,Recruiter,33500.0,10,4.9
46,47,Fathima K,Sales,Calicut,Executive,33500.0,3,3.8
49,50,Sreekanth Krishnan,HR,Kochi,Manager,28000.0,1,3.9
50,51,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,52,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,53,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
53,54,Lakshmi G,Sales,Thrissur,Manager,26000.0,5,3.9
54,55,Anoop K,Sales,Kochi,Senior Executive,29000.0,1,3.6
55,56,Deepa Thomas,Sales,Kochi,Manager,25500.0,12,4.1
56,57,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4
57,58,Ajay T,HR,Palakkad,Executive,30000.0,7,4.4
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [90]:
emp["Department"].value_counts()

Department
IT         19
Sales      18
HR         16
Finance     9
Name: count, dtype: int64

In [91]:
emp["City"].unique()

array(['Calicut', 'Kochi', 'Thrissur', nan, 'Palakkad', 'Kannur'],
      dtype=object)

In [92]:
emp["Exp_Yrs"].mean()

np.float64(6.032258064516129)